# Generated by Django 5.0.1 on 2024-06-13 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MonHoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauHoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255)),
                ('noi_dung', models.TextField(default='')),
                ('loai_cau_hoi', models.CharField(choices=[('TN', 'Trắc nghiệm'), ('DS', 'Đúng sai'), ('TL', 'Tự luận')], default='TN', max_length=2)),
                ('muc_do', models.CharField(choices=[('1', 'Nhận biết'), ('2', 'Thông hiểu'), ('3', 'Vận dụng')], default='1', max_length=1)),
                ('anh', models.ImageField(blank=True, null=True, upload_to='cauhoi_images/')),
                ('chuyenDe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonHoc.chuyende')),
            ],
        ),
        migrations.CreateModel(
            name='DapAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField(default='')),
                ('anh', models.ImageField(blank=True, null=True, upload_to='dapan_images/')),
                ('tinh_dung', models.BooleanField(default=False)),
                ('cauHoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NoiDung.cauhoi')),
            ],
        ),
        migrations.CreateModel(
            name='LyThuyet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255)),
                ('noi_dung', models.TextField(default='')),
                ('anh', models.ImageField(blank=True, null=True, upload_to='lythuyet_images/')),
                ('chuyenDe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonHoc.chuyende')),
            ],
        ),
        migrations.AddField(
            model_name='cauhoi',
            name='lyThuyet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NoiDung.lythuyet'),
        ),
    ]
