# Generated by Django 5.0.1 on 2024-06-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoiDung', '0002_cachgiai'),
    ]

    operations = [
        migrations.AddField(
            model_name='cauhoi',
            name='cach_giai',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='CachGiai',
        ),
    ]
