# Generated by Django 5.0.6 on 2024-07-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoiDung', '0003_cauhoi_cach_giai_delete_cachgiai'),
    ]

    operations = [
        migrations.AddField(
            model_name='dapan',
            name='vi_tri',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cauhoi',
            name='loai_cau_hoi',
            field=models.CharField(choices=[('TN', 'Trắc nghiệm'), ('DS', 'Đúng sai'), ('TL', 'Tự luận'), ('KT', 'Kéo thả')], default='TN', max_length=2),
        ),
    ]
