# Generated by Django 5.0.1 on 2024-07-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoiDung', '0003_cauhoi_cach_giai_delete_cachgiai'),
    ]

    operations = [
        migrations.AddField(
            model_name='dapan',
            name='thu_tu_dap_an',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cauhoi',
            name='loai_cau_hoi',
            field=models.CharField(choices=[('TN', 'Trắc nghiệm'), ('DS', 'Đúng sai'), ('TL', 'Tự luận'), ('DT', 'Điền từ')], default='TN', max_length=2),
        ),
    ]
