# Generated by Django 5.0.6 on 2024-07-11 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoiDung', '0004_dapan_thu_tu_dap_an_alter_cauhoi_loai_cau_hoi'),
        ('NoiDung', '0004_dapan_vi_tri_alter_cauhoi_loai_cau_hoi'),
    ]

    operations = [
    ]
