# Generated by Django 5.0.6 on 2024-07-11 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoiDung', '0005_merge_20240712_0532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dapan',
            name='vi_tri',
        ),
    ]
