# Generated by Django 5.0.6 on 2024-07-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoiDung', '0006_remove_dapan_vi_tri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauhoi',
            name='loai_cau_hoi',
            field=models.CharField(choices=[('TN', 'Trắc nghiệm'), ('CB', 'Đúng sai'), ('TL', 'Tự luận')], default='TN', max_length=2),
        ),
    ]
