# Generated by Django 5.0.6 on 2024-08-16 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanhGiaNangLuc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailam',
            name='luu_bai_thi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DanhGiaNangLuc.luotthi'),
        ),
    ]
