# Generated by Django 5.0.6 on 2024-07-20 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanhGiaNangLuc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luotthi',
            name='diem_so',
            field=models.FloatField(default=0, help_text='Điểm số từ 0 đến 10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
