# Generated by Django 5.0.6 on 2024-07-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanhGiaNangLuc', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonHoc',
        ),
        migrations.RemoveField(
            model_name='cauhoi',
            name='phan_thi',
        ),
        migrations.AddField(
            model_name='cauhoi',
            name='is_data_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cauhoi',
            name='language',
            field=models.CharField(blank=True, choices=[('vi', 'Tiếng Việt'), ('en', 'Tiếng Anh')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='cauhoi',
            name='subject',
            field=models.CharField(blank=True, choices=[('ly', 'Vật Lý'), ('hoa', 'Hóa Học'), ('sinh', 'Sinh Học'), ('su', 'Lịch Sử'), ('dia', 'Địa Lý'), ('gdcd', 'Giáo Dục Công Dân')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='cauhoi',
            name='noi_dung',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dapan',
            name='noi_dung',
            field=models.CharField(max_length=200),
        ),
    ]
