# Generated by Django 5.0.6 on 2024-07-15 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanhGiaNangLuc', '0002_delete_monhoc_remove_cauhoi_phan_thi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cauhoi',
            name='is_data_analysis',
        ),
        migrations.AddField(
            model_name='cauhoi',
            name='phan_2',
            field=models.CharField(blank=True, choices=[('TH', 'Toán học'), ('TDLG', 'Tư duy logic'), ('PTSL', 'Phân tích số liệu')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='noidungde',
            name='diem_so',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
