# Generated by Django 5.0.6 on 2024-08-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanhGiaNangLuc', '0002_alter_bailam_luu_bai_thi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauhoi',
            name='loai_cau_hoi',
            field=models.CharField(choices=[('TN', 'Trắc nghiệm'), ('CB', 'Đúng sai'), ('TL', 'Tự luận')], default='TN', max_length=2),
        ),
    ]
