# Generated by Django 5.0.6 on 2024-08-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanhGiaNangLuc', '0003_alter_cauhoi_loai_cau_hoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dethi',
            name='loai_de',
            field=models.CharField(choices=[('DGNL', 'Đánh giá năng lực HCM')], default='DGNL', max_length=50),
        ),
    ]
