# Generated by Django 5.0.1 on 2024-06-13 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Khoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khoi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mon', models.CharField(max_length=255)),
                ('mo_ta', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ChuyenDe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_chuyen_de', models.CharField(max_length=255)),
                ('mo_ta', models.CharField(default='', max_length=500)),
                ('khoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonHoc.khoi')),
                ('monHoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonHoc.monhoc')),
            ],
        ),
    ]
