# Generated by Django 5.0.1 on 2024-06-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonHoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chuyende',
            name='mo_ta',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='monhoc',
            name='mo_ta',
            field=models.TextField(default=''),
        ),
    ]
