# Generated by Django 5.0.1 on 2024-06-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonHoc', '0002_alter_chuyende_mo_ta_alter_monhoc_mo_ta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_bo_sach', models.CharField(max_length=255)),
                ('ten_nxb', models.CharField(max_length=255)),
                ('mo_ta', models.TextField(default='')),
            ],
        ),
    ]
