# Generated by Django 5.0.1 on 2024-06-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonHoc', '0003_sach'),
    ]

    operations = [
        migrations.AddField(
            model_name='sach',
            name='anh',
            field=models.ImageField(blank=True, null=True, upload_to='anh_images/'),
        ),
    ]
