# Generated by Django 5.0.1 on 2024-06-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonHoc', '0004_sach_anh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sach',
            name='anh',
            field=models.ImageField(null=True, upload_to='anh_images/'),
        ),
    ]
