# Generated by Django 5.0.6 on 2024-07-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanhGiaTuDuy', '0003_dethi_luotthi_noidungde_bailam_delete_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cauhoi',
            name='phan_thi',
            field=models.CharField(choices=[('TDTH', 'Tư duy toán học'), ('TDDH', 'Tư duy đọc hiểu'), ('TDKH', 'Tư duy khoa học')], default='TDTH', max_length=4),
        ),
    ]
