# Generated by Django 5.0.6 on 2024-07-11 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanhGiaTuDuy', '0004_cauhoi_phan_thi'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocHieuNoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255)),
                ('noi_dung', models.TextField()),
                ('anh', models.ImageField(blank=True, null=True, upload_to='dochieu_images/')),
            ],
        ),
        migrations.AddField(
            model_name='cauhoi',
            name='doc_hieu_noi_dung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DanhGiaTuDuy.dochieunoidung'),
        ),
    ]
