# Generated by Django 5.0.6 on 2024-07-12 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanhGiaTuDuy', '0006_remove_cauhoi_doc_hieu_noi_dung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noidungde',
            name='doc_hieu_noi_dung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DanhGiaTuDuy.dochieunoidung'),
        ),
    ]
