# Generated by Django 5.0.6 on 2024-07-12 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanhGiaTuDuy', '0007_noidungde_doc_hieu_noi_dung'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhoaHocNoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255)),
                ('noi_dung', models.TextField()),
                ('anh', models.ImageField(blank=True, null=True, upload_to='khoahoc_images/')),
            ],
        ),
        migrations.AddField(
            model_name='noidungde',
            name='khoa_hoc_noi_dung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DanhGiaTuDuy.khoahocnoidung'),
        ),
    ]
