# Generated by Django 5.0.6 on 2024-07-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanhGiaTuDuy', '0008_khoahocnoidung_noidungde_khoa_hoc_noi_dung'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailam',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
