# Generated by Django 5.0.6 on 2024-08-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanhGiaTuDuy', '0009_bailam_answer_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatexContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
