# Generated by Django 5.0.6 on 2024-08-22 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanhGiaTuDuy', '0011_delete_latexcontent_alter_cauhoi_loai_cau_hoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='dethi',
            name='ma_de',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
        ),
    ]
