# Generated by Django 5.0.1 on 2024-06-13 14:54

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NoiDung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_de_thi', models.CharField(max_length=255)),
                ('thoi_gia_thi', models.DurationField(default=datetime.timedelta(seconds=1800))),
            ],
        ),
        migrations.CreateModel(
            name='NoiDungDe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_so', models.FloatField(validators=[django.core.validators.MinValueValidator(0.001), django.core.validators.MaxValueValidator(10.0)])),
                ('thu_tu_cau', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='BaiLam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dap_an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NoiDung.dapan')),
            ],
        ),
    ]
