# Generated by Django 5.0.1 on 2024-06-13 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LuyenTap', '0001_initial'),
        ('MonHoc', '0001_initial'),
        ('NoiDung', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bailam',
            name='nguoi_lam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dethi',
            name='mon_thi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonHoc.monhoc'),
        ),
        migrations.AddField(
            model_name='bailam',
            name='de_thi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LuyenTap.dethi'),
        ),
        migrations.AddField(
            model_name='noidungde',
            name='cau_hoi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NoiDung.cauhoi'),
        ),
        migrations.AddField(
            model_name='noidungde',
            name='dap_an',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NoiDung.dapan'),
        ),
        migrations.AddField(
            model_name='noidungde',
            name='de_thi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LuyenTap.dethi'),
        ),
    ]
