# Generated by Django 5.0.1 on 2024-06-14 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuyenTap', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noidungde',
            name='dap_an',
        ),
        migrations.AlterField(
            model_name='noidungde',
            name='diem_so',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
