# Generated by Django 5.0.1 on 2024-06-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuyenTap', '0003_remove_noidungde_dap_an_alter_noidungde_diem_so'),
    ]

    operations = [
        migrations.AddField(
            model_name='dethi',
            name='trang_thai',
            field=models.BooleanField(default=False),
        ),
    ]
