# Generated by Django 5.0.1 on 2024-06-25 03:22

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuyenTap', '0004_dethi_trang_thai'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bailam',
            name='de_thi',
        ),
        migrations.RemoveField(
            model_name='bailam',
            name='nguoi_lam',
        ),
        migrations.CreateModel(
            name='LuuBaiThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_so', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('thoi_diem_thi', models.DateTimeField(default=django.utils.timezone.now)),
                ('thoi_gian_hoan_thanh', models.DurationField(default=datetime.timedelta(0))),
                ('so_cau_dung', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('de_thi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LuyenTap.dethi')),
                ('nguoi_lam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bailam',
            name='luu_bai_thi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LuyenTap.luubaithi'),
            preserve_default=False,
        ),
    ]
