# Generated by Django 5.0.1 on 2024-06-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuyenTap', '0005_remove_bailam_de_thi_remove_bailam_nguoi_lam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luubaithi',
            name='thoi_diem_thi',
            field=models.DateTimeField(default=0),
        ),
    ]
