# Generated by Django 5.0.1 on 2024-06-25 03:28

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuyenTap', '0006_alter_luubaithi_thoi_diem_thi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LuotThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_so', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('thoi_diem_thi', models.DateTimeField(default=0)),
                ('thoi_gian_hoan_thanh', models.DurationField(default=datetime.timedelta(0))),
                ('so_cau_dung', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('de_thi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LuyenTap.dethi')),
                ('nguoi_lam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='bailam',
            name='luu_bai_thi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LuyenTap.luotthi'),
        ),
        migrations.DeleteModel(
            name='LuuBaiThi',
        ),
    ]
