# Generated by Django 5.0.1 on 2024-06-25 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LuyenTap', '0007_luotthi_alter_bailam_luu_bai_thi_delete_luubaithi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luotthi',
            name='de_thi',
        ),
        migrations.RemoveField(
            model_name='luotthi',
            name='nguoi_lam',
        ),
        migrations.DeleteModel(
            name='BaiLam',
        ),
        migrations.DeleteModel(
            name='LuotThi',
        ),
    ]
