# Generated by Django 5.0.1 on 2024-06-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuyenTap', '0010_remove_bailam_de_thi_remove_bailam_nguoi_lam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dethi',
            name='loai_de',
            field=models.CharField(choices=[('HK', 'Đề kiểm tra học kì'), ('GK', 'Đề kiểm tra giữa kì'), ('KSCL', 'Đề khảo sát chất lượng đầu năm'), ('KT15P', 'Đề kiểm tra 15 phút'), ('KT1T', 'Đề kiểm tra 1 tiết')], default='GK', max_length=50),
        ),
    ]
