# Generated by Django 5.0.1 on 2024-06-29 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuyenTap', '0011_dethi_loai_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailam',
            name='noi_dung_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LuyenTap.noidungde'),
        ),
        migrations.AddField(
            model_name='bailam',
            name='tinh_dung',
            field=models.BooleanField(default=False),
        ),
    ]
