# Generated by Django 5.0.1 on 2024-06-29 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuyenTap', '0012_bailam_noi_dung_de_bailam_tinh_dung'),
        ('MonHoc', '0003_sach'),
    ]

    operations = [
        migrations.AddField(
            model_name='dethi',
            name='sach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MonHoc.sach'),
        ),
    ]
