# Generated by Django 5.0.6 on 2024-07-20 23:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuyenTap', '0015_rename_thoi_gia_thi_dethi_thoi_gian_thi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dethi',
            name='ma_de',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
        ),
    ]
