# Generated by Django 5.0.6 on 2024-07-20 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuyenTap', '0016_dethi_ma_de'),
        ('NoiDung', '0006_remove_dapan_vi_tri'),
    ]

    operations = [
        migrations.AddField(
            model_name='dethi',
            name='lyThuyet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NoiDung.lythuyet'),
        ),
    ]
