# Generated by Django 5.0.6 on 2024-07-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuyenTap', '0017_dethi_lythuyet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailam',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
